.POSIX:

## include

# rules 和 definitions 都可以 include
# source 其他的 makefile `.` (dot)

include a.makefile
include b.makefile

# 如果 file 不存在，会产生 error

# include idontexit
# 可通过 `-` 进行忽略

-include idontexit-but-you-ignore-me
